schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "02-conveyor-belt"
owner:
  username: "MAAJN"
  id: 322120654
  accepted_at: "2026-09-09T13:08:29Z"
source:
  owner: "dtucprog"
  owner_id: 316954301
  repo: "02-conveyor-belt"
  branch: "main"
